import { Parent, ParentMeeting } from '@/types';

export const mockParents: Parent[] = [
  {
    id: 'par-1',
    name: 'Robert Johnson',
    email: 'robert.j@email.com',
    phone: '+1 (555) 201-1001',
    relationship: 'father',
    occupation: 'Software Engineer',
    address: '123 Oak Street, Springfield, IL 62701',
    studentIds: ['std-1'],
    avatar: 'https://i.pravatar.cc/150?u=robert',
    status: 'active',
    registeredDate: '2021-08-15',
  },
  {
    id: 'par-2',
    name: 'Sarah Brown',
    email: 'sarah.b@email.com',
    phone: '+1 (555) 202-2001',
    relationship: 'mother',
    occupation: 'Teacher',
    address: '456 Pine Avenue, Springfield, IL 62701',
    studentIds: ['std-2'],
    avatar: 'https://i.pravatar.cc/150?u=sarahb',
    status: 'active',
    registeredDate: '2021-08-15',
  },
  {
    id: 'par-3',
    name: 'Carlos Martinez',
    email: 'carlos.m@email.com',
    phone: '+1 (555) 203-3001',
    relationship: 'father',
    occupation: 'Business Owner',
    address: '789 Maple Road, Portland, OR 97201',
    studentIds: ['std-3'],
    avatar: 'https://i.pravatar.cc/150?u=carlos',
    status: 'active',
    registeredDate: '2022-08-01',
  },
  {
    id: 'par-4',
    name: 'Jennifer Davis',
    email: 'jennifer.d@email.com',
    phone: '+1 (555) 204-4001',
    relationship: 'mother',
    occupation: 'Doctor',
    address: '321 Elm Street, Portland, OR 97201',
    studentIds: ['std-4'],
    avatar: 'https://i.pravatar.cc/150?u=jennifer',
    status: 'active',
    registeredDate: '2020-08-01',
  },
  {
    id: 'par-5',
    name: 'David Wilson',
    email: 'david.w@email.com',
    phone: '+1 (555) 205-5001',
    relationship: 'father',
    occupation: 'Architect',
    address: '654 Birch Lane, Seattle, WA 98101',
    studentIds: ['std-5'],
    avatar: 'https://i.pravatar.cc/150?u=davidw',
    status: 'active',
    registeredDate: '2023-08-20',
  },
];

export const mockParentMeetings: ParentMeeting[] = [
  {
    id: 'pm-1',
    parentId: 'par-1',
    teacherId: 'teacher-1',
    teacherName: 'John Smith',
    studentId: 'std-1',
    studentName: 'Emma Johnson',
    date: '2024-02-05',
    time: '14:00',
    purpose: 'Discuss academic progress and exam preparation',
    status: 'scheduled',
  },
  {
    id: 'pm-2',
    parentId: 'par-2',
    teacherId: 'teacher-2',
    teacherName: 'Maria Garcia',
    studentId: 'std-2',
    studentName: 'Michael Brown',
    date: '2024-01-25',
    time: '10:30',
    purpose: 'Behavior discussion and improvement plan',
    status: 'completed',
    notes: 'Productive meeting. Parent agreed to monitor homework completion.',
  },
  {
    id: 'pm-3',
    parentId: 'par-3',
    teacherId: 'teacher-3',
    teacherName: 'David Lee',
    studentId: 'std-3',
    studentName: 'Sophia Martinez',
    date: '2024-02-10',
    time: '15:30',
    purpose: 'Discuss extracurricular activities',
    status: 'scheduled',
  },
];
