import { School } from '@/types';

export const mockSchools: School[] = [
  {
    id: '1',
    name: 'Greenwood High School',
    address: '123 Main Street, Springfield, IL 62701',
    contactEmail: 'admin@greenwood.edu',
    contactPhone: '+1 (555) 123-4567',
    principalName: 'Dr. Sarah Johnson',
    studentCount: 850,
    teacherCount: 65,
    establishedDate: '2005-08-15',
    status: 'active',
    subscription: 'premium',
    logo: 'https://i.pravatar.cc/150?u=greenwood',
  },
  {
    id: '2',
    name: 'Riverside Academy',
    address: '456 Oak Avenue, Portland, OR 97201',
    contactEmail: 'contact@riverside.edu',
    contactPhone: '+1 (555) 234-5678',
    principalName: 'Mr. Michael Chen',
    studentCount: 620,
    teacherCount: 48,
    establishedDate: '2010-09-01',
    status: 'active',
    subscription: 'enterprise',
    logo: 'https://i.pravatar.cc/150?u=riverside',
  },
  {
    id: '3',
    name: 'Maple Leaf Elementary',
    address: '789 Pine Road, Seattle, WA 98101',
    contactEmail: 'hello@mapleleaf.edu',
    contactPhone: '+1 (555) 345-6789',
    principalName: 'Mrs. Emily Williams',
    studentCount: 420,
    teacherCount: 32,
    establishedDate: '2012-01-10',
    status: 'active',
    subscription: 'basic',
    logo: 'https://i.pravatar.cc/150?u=mapleleaf',
  },
  {
    id: '4',
    name: 'Summit Learning Center',
    address: '321 Elm Street, Denver, CO 80201',
    contactEmail: 'info@summitlc.edu',
    contactPhone: '+1 (555) 456-7890',
    principalName: 'Dr. Robert Martinez',
    studentCount: 980,
    teacherCount: 78,
    establishedDate: '2008-06-20',
    status: 'active',
    subscription: 'enterprise',
    logo: 'https://i.pravatar.cc/150?u=summit',
  },
  {
    id: '5',
    name: 'Lakeside Middle School',
    address: '654 Birch Lane, Austin, TX 78701',
    contactEmail: 'admin@lakeside.edu',
    contactPhone: '+1 (555) 567-8901',
    principalName: 'Ms. Jennifer Brown',
    studentCount: 540,
    teacherCount: 42,
    establishedDate: '2015-03-12',
    status: 'inactive',
    subscription: 'basic',
    logo: 'https://i.pravatar.cc/150?u=lakeside',
  },
  {
    id: '6',
    name: 'Phoenix International School',
    address: '987 Cedar Drive, Boston, MA 02101',
    contactEmail: 'contact@phoenix.edu',
    contactPhone: '+1 (555) 678-9012',
    principalName: 'Dr. James Wilson',
    studentCount: 1120,
    teacherCount: 92,
    establishedDate: '2003-11-05',
    status: 'active',
    subscription: 'enterprise',
    logo: 'https://i.pravatar.cc/150?u=phoenix',
  },
  {
    id: '7',
    name: 'Valley View Academy',
    address: '147 Maple Court, San Francisco, CA 94101',
    contactEmail: 'hello@valleyview.edu',
    contactPhone: '+1 (555) 789-0123',
    principalName: 'Mrs. Patricia Davis',
    studentCount: 730,
    teacherCount: 58,
    establishedDate: '2011-04-18',
    status: 'active',
    subscription: 'premium',
    logo: 'https://i.pravatar.cc/150?u=valleyview',
  },
  {
    id: '8',
    name: 'Bright Future Elementary',
    address: '258 Willow Way, Miami, FL 33101',
    contactEmail: 'info@brightfuture.edu',
    contactPhone: '+1 (555) 890-1234',
    principalName: 'Mr. David Thompson',
    studentCount: 380,
    teacherCount: 28,
    establishedDate: '2016-07-22',
    status: 'active',
    subscription: 'basic',
    logo: 'https://i.pravatar.cc/150?u=brightfuture',
  },
];
