import { Student, AcademicRecord, AttendanceRecord } from '@/types';

export const mockStudents: Student[] = [
  {
    id: 'std-1',
    name: 'Emma Johnson',
    email: 'emma.j@student.greenwood.edu',
    schoolId: '1',
    schoolName: 'Greenwood High School',
    grade: '10th',
    class: 'A',
    rollNumber: 'GHS-10A-001',
    dateOfBirth: '2009-03-15',
    parentId: 'par-1',
    parentName: 'Robert Johnson',
    parentEmail: 'robert.j@email.com',
    parentPhone: '+1 (555) 201-1001',
    avatar: 'https://i.pravatar.cc/150?u=emma',
    status: 'active',
    enrollmentDate: '2021-09-01',
    address: '123 Oak Street, Springfield, IL 62701',
    bloodGroup: 'O+',
    emergencyContact: '+1 (555) 201-1002',
  },
  {
    id: 'std-2',
    name: 'Michael Brown',
    email: 'michael.b@student.greenwood.edu',
    schoolId: '1',
    schoolName: 'Greenwood High School',
    grade: '10th',
    class: 'B',
    rollNumber: 'GHS-10B-015',
    dateOfBirth: '2009-07-22',
    parentId: 'par-2',
    parentName: 'Sarah Brown',
    parentEmail: 'sarah.b@email.com',
    parentPhone: '+1 (555) 202-2001',
    avatar: 'https://i.pravatar.cc/150?u=michael',
    status: 'active',
    enrollmentDate: '2021-09-01',
    address: '456 Pine Avenue, Springfield, IL 62701',
    bloodGroup: 'A+',
    emergencyContact: '+1 (555) 202-2002',
  },
  {
    id: 'std-3',
    name: 'Sophia Martinez',
    email: 'sophia.m@student.riverside.edu',
    schoolId: '2',
    schoolName: 'Riverside Academy',
    grade: '9th',
    class: 'A',
    rollNumber: 'RA-09A-008',
    dateOfBirth: '2010-01-10',
    parentId: 'par-3',
    parentName: 'Carlos Martinez',
    parentEmail: 'carlos.m@email.com',
    parentPhone: '+1 (555) 203-3001',
    avatar: 'https://i.pravatar.cc/150?u=sophia',
    status: 'active',
    enrollmentDate: '2022-08-28',
    address: '789 Maple Road, Portland, OR 97201',
    bloodGroup: 'B+',
    emergencyContact: '+1 (555) 203-3002',
  },
  {
    id: 'std-4',
    name: 'William Davis',
    email: 'william.d@student.riverside.edu',
    schoolId: '2',
    schoolName: 'Riverside Academy',
    grade: '11th',
    class: 'C',
    rollNumber: 'RA-11C-022',
    dateOfBirth: '2008-11-05',
    parentId: 'par-4',
    parentName: 'Jennifer Davis',
    parentEmail: 'jennifer.d@email.com',
    parentPhone: '+1 (555) 204-4001',
    avatar: 'https://i.pravatar.cc/150?u=william',
    status: 'active',
    enrollmentDate: '2020-08-28',
    address: '321 Elm Street, Portland, OR 97201',
    bloodGroup: 'AB+',
    emergencyContact: '+1 (555) 204-4002',
  },
  {
    id: 'std-5',
    name: 'Olivia Wilson',
    email: 'olivia.w@student.mapleleaf.edu',
    schoolId: '3',
    schoolName: 'Maple Leaf Elementary',
    grade: '5th',
    class: 'B',
    rollNumber: 'MLE-05B-012',
    dateOfBirth: '2014-05-18',
    parentId: 'par-5',
    parentName: 'David Wilson',
    parentEmail: 'david.w@email.com',
    parentPhone: '+1 (555) 205-5001',
    avatar: 'https://i.pravatar.cc/150?u=olivia',
    status: 'active',
    enrollmentDate: '2023-09-05',
    address: '654 Birch Lane, Seattle, WA 98101',
    bloodGroup: 'O-',
    emergencyContact: '+1 (555) 205-5002',
  },
];

export const mockAcademicRecords: AcademicRecord[] = [
  // Emma's records
  { id: 'ar-1', studentId: 'std-1', subject: 'Mathematics', marks: 92, totalMarks: 100, grade: 'A+', term: 'Mid-term', year: '2024' },
  { id: 'ar-2', studentId: 'std-1', subject: 'English', marks: 88, totalMarks: 100, grade: 'A', term: 'Mid-term', year: '2024' },
  { id: 'ar-3', studentId: 'std-1', subject: 'Science', marks: 95, totalMarks: 100, grade: 'A+', term: 'Mid-term', year: '2024' },
  { id: 'ar-4', studentId: 'std-1', subject: 'History', marks: 85, totalMarks: 100, grade: 'A', term: 'Mid-term', year: '2024' },
  
  // Michael's records
  { id: 'ar-5', studentId: 'std-2', subject: 'Mathematics', marks: 78, totalMarks: 100, grade: 'B+', term: 'Mid-term', year: '2024' },
  { id: 'ar-6', studentId: 'std-2', subject: 'English', marks: 82, totalMarks: 100, grade: 'A-', term: 'Mid-term', year: '2024' },
  { id: 'ar-7', studentId: 'std-2', subject: 'Science', marks: 80, totalMarks: 100, grade: 'A-', term: 'Mid-term', year: '2024' },
  { id: 'ar-8', studentId: 'std-2', subject: 'History', marks: 75, totalMarks: 100, grade: 'B+', term: 'Mid-term', year: '2024' },
];

export const mockAttendance: AttendanceRecord[] = [
  { id: 'att-1', studentId: 'std-1', date: '2024-01-29', status: 'present' },
  { id: 'att-2', studentId: 'std-1', date: '2024-01-28', status: 'present' },
  { id: 'att-3', studentId: 'std-1', date: '2024-01-27', status: 'present' },
  { id: 'att-4', studentId: 'std-2', date: '2024-01-29', status: 'late', remarks: 'Arrived 10 minutes late' },
  { id: 'att-5', studentId: 'std-2', date: '2024-01-28', status: 'present' },
];
