import { User } from '@/types';

export const mockUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Admin User',
    email: 'admin@school-system.com',
    role: 'super_admin',
    schoolId: null,
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=admin1',
    joinedDate: '2020-01-15',
    phone: '+1 (555) 100-0001',
  },
  {
    id: 'school-admin-1',
    name: 'Dr. Sarah Johnson',
    email: 'sarah.johnson@greenwood.edu',
    role: 'school_admin',
    schoolId: '1',
    schoolName: 'Greenwood High School',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=sjohnson',
    joinedDate: '2005-08-15',
    phone: '+1 (555) 123-4567',
  },
  {
    id: 'teacher-1',
    name: 'John Smith',
    email: 'john.smith@greenwood.edu',
    role: 'teacher',
    schoolId: '1',
    schoolName: 'Greenwood High School',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=jsmith',
    joinedDate: '2018-08-20',
    phone: '+1 (555) 201-0001',
  },
  {
    id: 'student-1',
    name: 'Emma Johnson',
    email: 'emma.j@student.greenwood.edu',
    role: 'student',
    schoolId: '1',
    schoolName: 'Greenwood High School',
    status: 'active',
    avatar: 'https://i.pravatar.cc/150?u=ejohnson',
    joinedDate: '2021-09-01',
  },
];
